[build]
  # Your site doesn't have a build step, so command can be omitted or empty
  # command = ""
  publish = "." # Serve files from the root directory

[build.environment]
  # Good to specify a Node.js version for consistency in Netlify's build environment
  # Even if you're not using Node directly, plugins might.
  NODE_VERSION = "18" # Or "20"

# If you decide to use other plugins in the future, you'd list them here:
# [[plugins]]
#   package = "some-other-plugin"
